name: UnitedShops
version: 0.0.2
vuthor: DerHerrFuchss
main: io.github.nexadn.unitedshops.UnitedShops
commands:
  ushopdebug:
    description: Debug command
    permission: unitedshops.admin
    usage: "Usage: /ushopdebug [command] [Args...]"

depend: [Vault]
loadbefore: [Vault]