name: UnitedShops
version: 1.5
author: NexAdn
main: io.github.nexadn.unitedshops.UnitedShops
description: Admin shop plugins
commands:
  ushop:
    description: Open the AdminShop
    permission: unitedshops.useshop
    usage: "Usage: /ushop"
  usell:
    description: Open the automatic sale dialog
    permission: unitedshops.autosell
    usage: "Usage: /usell"
  ushopreload:
    description: Reload and applay the configuration files
    permission: unitedshops.admin
    usage: "Usage: /ushopreload"
depend:
- Vault 
loadbefore: 
- Vault
