name: UnitedShops
main: me.nexadn.unitedshops.UnitedShops
version: 2.0.0
author: NexAdn
commands:
  shop:
    description: Open the shop
    usgae: /shop
  unitedshops:
    description: Main unitedshops command
    usage: /unitedshops <shop|autosell|reload>
    
depend:
- Vault
loadBefore:
- Vault