name: UnitedShops
version: 1.0.0
author: NexAdn
main: io.github.nexadn.unitedshops.UnitedShops
commands:
  ushop:
    description: Open the AdminShop
    permission: unitedshops.useshop
    usage: "Usage: /ushop"
  usell:
    description: Open the automatic sale dialog
    permission: unitedshops.autosell
    usage: "Usage: /usell"

depend:
- Vault 
loadbefore: 
- Vault