name: UnitedShops
main: me.nexadn.unitedshops.UnitedShops
version: ${project.version}
author: NexAdn
commands:
  shop:
    description: Open the shop
    usgae: /shop
  unitedshops:
    description: Main unitedshops command
    usage: /unitedshops <shop|sell|reload>

depend:
- Vault
loadBefore:
- Vault
