name: UnitedShops
version: 1.0.0
author: NexAdn
main: io.github.nexadn.unitedshops.UnitedShops
commands:
  ushop:
    description: Open the AdminShop
    permission: unitedshops.useshop
    usage: "Usage: /ushop"

depend:
- Vault 
loadbefore: 
- Vault