name: UnitedShops
version: 2.0.0
author: NexAdn
main: io.github.nexadn.unitedshops.UnitedShops
description: Admin shop plugins
commands:
  ushop:
    description: Open the AdminShop
    permission: unitedshops.useshop
    usage: "Usage: /ushop"
  usell:
    description: Open the automatic sale dialog
    permission: unitedshops.autosell
    usage: "Usage: /usell"
  ushopreload:
    description: Reload and applay the configuration files
    permission: unitedshops.admin
    usage: "Usage: /ushopreload"
  ushopoffer:
    description: Open a new offer
    permission: unitedshops.admin
    usage: "Usage: /ushopoffer"
  uvmenu:
    description: Open the global vendor menu
    permission: unitedshops.admin
    usage: "Usage: /uvmenu"
  uomenu:
    description: Open the global offer menu
    permission: unitedshops.admin
    usage: "Usage: /uomenu"
  uosupply:
    description: Supply an offer
    permission: unitedshops.admin
    usage: "Usage: /uosupply"
depend:
- Vault 
loadbefore: 
- Vault
